packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  "@biomejs/biome": ^1.9.4
  "@hono/node-server": ^1.14.0
  "@hono/trpc-server": ^0.3.4
  "@playwright/test": ^1.42.1
  "@radix-ui/react-avatar": ^1.1.3
  "@radix-ui/react-dialog": ^1.1.6
  "@radix-ui/react-dropdown-menu": ^2.1.6
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.2
  "@radix-ui/react-slot": ^1.1.2
  "@radix-ui/react-toast": ^1.2.6
  "@radix-ui/react-tooltip": ^1.1.8
  "@tailwindcss/vite": ^4.1.3
  "@tanstack/react-form": ^1.3.0
  "@tanstack/react-query": ^5.71.10
  "@tanstack/react-router": ^1.114.34
  "@tanstack/router-devtools": ^1.114.34
  "@tanstack/router-plugin": ^1.114.34
  "@testing-library/react": ^14.2.1
  "@trpc/client": ^11.0.2
  "@trpc/server": ^11.0.2
  "@trpc/tanstack-react-query": ^11.0.2
  "@types/node": ^22.14.0
  "@types/pg": ^8.11.11
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1
  "@vitejs/plugin-react-swc": ^3.8.1
  "@vitest/coverage-istanbul": ^3.0.7
  "@vitest/ui": ^3.0.7
  better-auth: ^1.2.5
  class-variance-authority: ^0.7.1
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  drizzle-valibot: ^0.4.1
  glob: ^11.0.1
  globals: ^16.0.0
  hono: ^4.7.5
  jsdom: ^26.0.0
  next-themes: ^0.4.6
  nyc: ^17.1.0
  pg: ^8.14.1
  radix-ui: ^1.1.3
  react: ^19.1.0
  react-dom: ^19.1.0
  shx: ^0.4.0
  sonner: ^2.0.3
  superjson: ^2.2.2
  tailwind-merge: ^3.1.0
  tailwindcss: ^4.1.3
  tailwindcss-animate: ^1.0.7
  tsup: ^8.4.0
  tsx: ^4.19.3
  turbo: ^2.5.0
  tw-animate-css: ^1.2.5
  typescript: ^5.4.5
  url-join: ^5.0.0
  valibot: ^1.0.0
  vite: ^6.2.5
  vitest: ^3.0.7
